[server]
name = "arduino"
version = "v1"

[configuration]
port = "50056"
run = "python3 ./main.py" # This is the run command, can use any language this way
proto = "./proto" # This is the directory where the proto files are contained
requests_to_influx = true # This is to send any incoming requests to influx, this goes through the manager 