[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hpcontrol_python_server"
version = "1.3"
description = "Generated Python code from proto files"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.7"
