// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: arduino.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_arduino_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arduino_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_arduino_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_arduino_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_arduino_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_arduino_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_arduino_proto protoreflect.FileDescriptor

const file_arduino_proto_rawDesc = "" +
	"\n" +
	"\rarduino.proto\x12\aarduino\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x82\x01\n" +
	"\aGreeter\x128\n" +
	"\bSayHello\x12\x15.arduino.HelloRequest\x1a\x13.arduino.HelloReply\"\x00\x12=\n" +
	"\rSayHelloAgain\x12\x15.arduino.HelloRequest\x1a\x13.arduino.HelloReply\"\x00B2\n" +
	"\x11io.arduino.clientB\fArduinoProtoP\x01Z\rarduino/hellob\x06proto3"

var (
	file_arduino_proto_rawDescOnce sync.Once
	file_arduino_proto_rawDescData []byte
)

func file_arduino_proto_rawDescGZIP() []byte {
	file_arduino_proto_rawDescOnce.Do(func() {
		file_arduino_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arduino_proto_rawDesc), len(file_arduino_proto_rawDesc)))
	})
	return file_arduino_proto_rawDescData
}

var file_arduino_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_arduino_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: arduino.HelloRequest
	(*HelloReply)(nil),   // 1: arduino.HelloReply
}
var file_arduino_proto_depIdxs = []int32{
	0, // 0: arduino.Greeter.SayHello:input_type -> arduino.HelloRequest
	0, // 1: arduino.Greeter.SayHelloAgain:input_type -> arduino.HelloRequest
	1, // 2: arduino.Greeter.SayHello:output_type -> arduino.HelloReply
	1, // 3: arduino.Greeter.SayHelloAgain:output_type -> arduino.HelloReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arduino_proto_init() }
func file_arduino_proto_init() {
	if File_arduino_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arduino_proto_rawDesc), len(file_arduino_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arduino_proto_goTypes,
		DependencyIndexes: file_arduino_proto_depIdxs,
		MessageInfos:      file_arduino_proto_msgTypes,
	}.Build()
	File_arduino_proto = out.File
	file_arduino_proto_goTypes = nil
	file_arduino_proto_depIdxs = nil
}
