# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: arduino.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class HelloRequest(betterproto.Message):
    """The request message containing the user's name."""

    name: str = betterproto.string_field(1)


@dataclass
class HelloReply(betterproto.Message):
    """The response message containing the greetings"""

    message: str = betterproto.string_field(1)


class GreeterStub(betterproto.ServiceStub):
    """The greeting service definition."""

    async def say_hello(self, *, name: str = "") -> HelloReply:
        """Sends a greeting"""

        request = HelloRequest()
        request.name = name

        return await self._unary_unary(
            "/arduino.Greeter/SayHello",
            request,
            HelloReply,
        )

    async def say_hello_again(self, *, name: str = "") -> HelloReply:
        request = HelloRequest()
        request.name = name

        return await self._unary_unary(
            "/arduino.Greeter/SayHelloAgain",
            request,
            HelloReply,
        )
