[project]
name = "uv2nix-template"
version = "0.1.0"
requires-python = ">=3.10,<3.12"
dependencies = [
    "setuptools",
    "artiq @ git+https://github.com/m-labs/artiq.git@8.0",
    "artiq-comtools @ git+https://github.com/m-labs/artiq-comtools.git",
    "sipyco @ git+https://github.com/m-labs/sipyco.git",
    "pythonparser @ git+https://github.com/m-labs/pythonparser.git",
    "numpy>=1.20.0",
    "llvmlite>=0.44.0",
    #"pyqt5-qt5 >= 5.15.2",
    #"pyqt5-sip >= 12.12.2"
    "pyqt5>=5.15.11",
]

# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-optional-dependencies
#[project.optional-dependencies]
#PySide6-Essentials = [
#  "PySide6-Essentials >= 6.0.0",
#]
#PyQt6 = [
#  "PyQt6 >= 6.0.0",
#]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
