[project]
dependencies = [
    "setuptools",
    "artiq @ git+https://gitlab.com/aion-physics/code/artiq/forks/artiq_fork.git",
    "sipyco @ git+https://github.com/m-labs/sipyco.git",
    "pythonparser @ git+https://github.com/m-labs/pythonparser.git",
    "numpy>=1.20.0",
    "llvmlite>=0.44.0",
    "PyQt6>=6.4.0"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
