// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: otter.proto

package otter_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivateServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateServicesRequest) Reset() {
	*x = ActivateServicesRequest{}
	mi := &file_otter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateServicesRequest) ProtoMessage() {}

func (x *ActivateServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateServicesRequest.ProtoReflect.Descriptor instead.
func (*ActivateServicesRequest) Descriptor() ([]byte, []int) {
	return file_otter_proto_rawDescGZIP(), []int{0}
}

type ActiveServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceDefinition   `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveServicesResponse) Reset() {
	*x = ActiveServicesResponse{}
	mi := &file_otter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveServicesResponse) ProtoMessage() {}

func (x *ActiveServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveServicesResponse.ProtoReflect.Descriptor instead.
func (*ActiveServicesResponse) Descriptor() ([]byte, []int) {
	return file_otter_proto_rawDescGZIP(), []int{1}
}

func (x *ActiveServicesResponse) GetServices() []*ServiceDefinition {
	if x != nil {
		return x.Services
	}
	return nil
}

type HeartbeatPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_otter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_otter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_otter_proto_rawDescGZIP(), []int{2}
}

type HeartbeatPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_otter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_otter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_otter_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatPong) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type ServiceDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	File          *File                  `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDefinition) Reset() {
	*x = ServiceDefinition{}
	mi := &file_otter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDefinition) ProtoMessage() {}

func (x *ServiceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_otter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDefinition.ProtoReflect.Descriptor instead.
func (*ServiceDefinition) Descriptor() ([]byte, []int) {
	return file_otter_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceDefinition) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceDefinition) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceDefinition) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceDefinition     `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_otter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_otter_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRequest) GetService() *ServiceDefinition {
	if x != nil {
		return x.Service
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_otter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_otter_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type StubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"` // e.g., "python", "java"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StubRequest) Reset() {
	*x = StubRequest{}
	mi := &file_otter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StubRequest) ProtoMessage() {}

func (x *StubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StubRequest.ProtoReflect.Descriptor instead.
func (*StubRequest) Descriptor() ([]byte, []int) {
	return file_otter_proto_rawDescGZIP(), []int{7}
}

func (x *StubRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *StubRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StubRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_otter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_otter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_otter_proto_rawDescGZIP(), []int{8}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type StubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"` // Changed from single bytes to repeated files
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StubResponse) Reset() {
	*x = StubResponse{}
	mi := &file_otter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StubResponse) ProtoMessage() {}

func (x *StubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StubResponse.ProtoReflect.Descriptor instead.
func (*StubResponse) Descriptor() ([]byte, []int) {
	return file_otter_proto_rawDescGZIP(), []int{9}
}

func (x *StubResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_otter_proto protoreflect.FileDescriptor

const file_otter_proto_rawDesc = "" +
	"\n" +
	"\votter.proto\x12\x05otter\"\x19\n" +
	"\x17ActivateServicesRequest\"N\n" +
	"\x16ActiveServicesResponse\x124\n" +
	"\bservices\x18\x01 \x03(\v2\x18.otter.ServiceDefinitionR\bservices\"\x0f\n" +
	"\rHeartbeatPing\")\n" +
	"\rHeartbeatPong\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\"q\n" +
	"\x11ServiceDefinition\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\x04file\x18\x03 \x01(\v2\v.otter.FileR\x04file\"E\n" +
	"\x0fRegisterRequest\x122\n" +
	"\aservice\x18\x01 \x01(\v2\x18.otter.ServiceDefinitionR\aservice\"*\n" +
	"\x10RegisterResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"f\n" +
	"\vStubRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"4\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"1\n" +
	"\fStubResponse\x12!\n" +
	"\x05files\x18\x01 \x03(\v2\v.otter.FileR\x05files2\x8d\x02\n" +
	"\aManager\x122\n" +
	"\aGetStub\x12\x12.otter.StubRequest\x1a\x13.otter.StubResponse\x12A\n" +
	"\x0eRegisterServer\x12\x16.otter.RegisterRequest\x1a\x17.otter.RegisterResponse\x127\n" +
	"\tHeartbeat\x12\x14.otter.HeartbeatPing\x1a\x14.otter.HeartbeatPong\x12R\n" +
	"\x11GetActiveServices\x12\x1e.otter.ActivateServicesRequest\x1a\x1d.otter.ActiveServicesResponseB)\n" +
	"\x0fio.otter.clientB\x05OtterP\x01Z\rotter.managerb\x06proto3"

var (
	file_otter_proto_rawDescOnce sync.Once
	file_otter_proto_rawDescData []byte
)

func file_otter_proto_rawDescGZIP() []byte {
	file_otter_proto_rawDescOnce.Do(func() {
		file_otter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_otter_proto_rawDesc), len(file_otter_proto_rawDesc)))
	})
	return file_otter_proto_rawDescData
}

var file_otter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_otter_proto_goTypes = []any{
	(*ActivateServicesRequest)(nil), // 0: otter.ActivateServicesRequest
	(*ActiveServicesResponse)(nil),  // 1: otter.ActiveServicesResponse
	(*HeartbeatPing)(nil),           // 2: otter.HeartbeatPing
	(*HeartbeatPong)(nil),           // 3: otter.HeartbeatPong
	(*ServiceDefinition)(nil),       // 4: otter.ServiceDefinition
	(*RegisterRequest)(nil),         // 5: otter.RegisterRequest
	(*RegisterResponse)(nil),        // 6: otter.RegisterResponse
	(*StubRequest)(nil),             // 7: otter.StubRequest
	(*File)(nil),                    // 8: otter.File
	(*StubResponse)(nil),            // 9: otter.StubResponse
}
var file_otter_proto_depIdxs = []int32{
	4, // 0: otter.ActiveServicesResponse.services:type_name -> otter.ServiceDefinition
	8, // 1: otter.ServiceDefinition.file:type_name -> otter.File
	4, // 2: otter.RegisterRequest.service:type_name -> otter.ServiceDefinition
	8, // 3: otter.StubResponse.files:type_name -> otter.File
	7, // 4: otter.Manager.GetStub:input_type -> otter.StubRequest
	5, // 5: otter.Manager.RegisterServer:input_type -> otter.RegisterRequest
	2, // 6: otter.Manager.Heartbeat:input_type -> otter.HeartbeatPing
	0, // 7: otter.Manager.GetActiveServices:input_type -> otter.ActivateServicesRequest
	9, // 8: otter.Manager.GetStub:output_type -> otter.StubResponse
	6, // 9: otter.Manager.RegisterServer:output_type -> otter.RegisterResponse
	3, // 10: otter.Manager.Heartbeat:output_type -> otter.HeartbeatPong
	1, // 11: otter.Manager.GetActiveServices:output_type -> otter.ActiveServicesResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_otter_proto_init() }
func file_otter_proto_init() {
	if File_otter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_otter_proto_rawDesc), len(file_otter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_otter_proto_goTypes,
		DependencyIndexes: file_otter_proto_depIdxs,
		MessageInfos:      file_otter_proto_msgTypes,
	}.Build()
	File_otter_proto = out.File
	file_otter_proto_goTypes = nil
	file_otter_proto_depIdxs = nil
}
