# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: chaos_server.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "DelayRequest",
    "Empty",
    "ChaosServiceStub",
    "ChaosServiceBase",
)

from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2
import grpc
import grpclib
from betterproto2.grpc.grpclib_server import ServiceBase

from ..message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server

betterproto2.check_compiler_version("0.4.0")


@dataclass(eq=False, repr=False)
class DelayRequest(betterproto2.Message):
    delay: "float" = betterproto2.field(1, betterproto2.TYPE_FLOAT)


default_message_pool.register_message("chaos_server", "DelayRequest", DelayRequest)


@dataclass(eq=False, repr=False)
class Empty(betterproto2.Message):
    pass


default_message_pool.register_message("chaos_server", "empty", Empty)


class ChaosServiceStub:
    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def crash_server(self, message: "DelayRequest") -> "Empty":
        return self._channel.unary_unary(
            "/chaos_server.ChaosService/crash_server",
            DelayRequest.SerializeToString,
            Empty.FromString,
        )(message)

    def exit_server(self, message: "DelayRequest") -> "Empty":
        return self._channel.unary_unary(
            "/chaos_server.ChaosService/exit_server",
            DelayRequest.SerializeToString,
            Empty.FromString,
        )(message)

    def abort_server(self, message: "DelayRequest") -> "Empty":
        return self._channel.unary_unary(
            "/chaos_server.ChaosService/abort_server",
            DelayRequest.SerializeToString,
            Empty.FromString,
        )(message)

    def hang_server(self, message: "DelayRequest") -> "Empty":
        return self._channel.unary_unary(
            "/chaos_server.ChaosService/hang_server",
            DelayRequest.SerializeToString,
            Empty.FromString,
        )(message)


class ChaosServiceBase(ServiceBase):
    async def crash_server(self, message: "DelayRequest") -> "Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def exit_server(self, message: "DelayRequest") -> "Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def abort_server(self, message: "DelayRequest") -> "Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def hang_server(self, message: "DelayRequest") -> "Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_crash_server(
        self, stream: "grpclib.server.Stream[DelayRequest, Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.crash_server(request)
        await stream.send_message(response)

    async def __rpc_exit_server(
        self, stream: "grpclib.server.Stream[DelayRequest, Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.exit_server(request)
        await stream.send_message(response)

    async def __rpc_abort_server(
        self, stream: "grpclib.server.Stream[DelayRequest, Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.abort_server(request)
        await stream.send_message(response)

    async def __rpc_hang_server(
        self, stream: "grpclib.server.Stream[DelayRequest, Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.hang_server(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/chaos_server.ChaosService/crash_server": grpclib.const.Handler(
                self.__rpc_crash_server,
                grpclib.const.Cardinality.UNARY_UNARY,
                DelayRequest,
                Empty,
            ),
            "/chaos_server.ChaosService/exit_server": grpclib.const.Handler(
                self.__rpc_exit_server,
                grpclib.const.Cardinality.UNARY_UNARY,
                DelayRequest,
                Empty,
            ),
            "/chaos_server.ChaosService/abort_server": grpclib.const.Handler(
                self.__rpc_abort_server,
                grpclib.const.Cardinality.UNARY_UNARY,
                DelayRequest,
                Empty,
            ),
            "/chaos_server.ChaosService/hang_server": grpclib.const.Handler(
                self.__rpc_hang_server,
                grpclib.const.Cardinality.UNARY_UNARY,
                DelayRequest,
                Empty,
            ),
        }
